apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-full-access-sa
  namespace: ml # Change this if you need it in a different namespace
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::880335327306:role/eks-s3-full
