apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: churn-predictor
  namespace: ml
spec:
  predictor:
    serviceAccountName: s3-full-access-sa
    sklearn:
      storageUri: s3://model-bucket-mlops-vignesh/models/churn_model.pkl